### PR TITLE
Latest work on dialogs

### PR DESCRIPTION
**Pull request by xgrg**
So now this pull request is supposed to be from my personal branch named 'dialog' to the main repo's master branch.
Here is a copy of my last commit message. 
- blink.py is an ad-hoc example on how to use a timer to trigger periodic events
- dialog.py is a short example on how to create a dialog box without anything else
- timer_and_space.py example is now in the examples/ directory

Classes such as DialogState, DialogListener, DialogContext are now in a specific file called dialog.py. A DialogContext sets all necessary dynamic transitions (transitions between states, toggling the '...' dots, the SPACE key effect (calling next DialogState / cancelling the typing machine mode (displaying the rest of the text at once), ...)

The function Context.set_visible(sprite, _is_visible, layer=None) allows to register/unregister a sprite in the context list of visible data. Context.set_visible(sprite, True) is equal to Context.add_visible_data(sprite).

Examples were updated following this new Dialog API.

### CODE REVIEW

**Comment by MatthieuPerrot** [comment]
Youhou ! We are close to a fully working dialog box !

In the following, this is the comments I remember from yesterday:
- move DialogContext somewhere else in a new directory. Your suggestion "$NURSEDIR/nurse/game" is good for me
- create a BlinkText sprite: until we don't have a good integration of timers, I think we should use the update(dt) strategy. Then, update the example accordingly.
- we could use this BlinkText sprite in the "dialog" example for the "..." text.
- remove/rework DialogListener and make a proposal based on «conditional states transition» using property values (maybe in a new branch created from main repository master ?).
- cleaning up: remove some remaining print/debug stuff.

I think the further works we talk about about actions and their integration in dialogs ("%1") should be done in a second stage after resolving this pull resquest.

**Comment by xgrg** [comment]
There are still a few things that I don't get very well in the history stuff (e.g. why 6a6c3df and 4fd0aa6 curiously look alike), well...

Still, finally the output of last night's work tries to bring new features to the dialog system :
- the appearance of the dialog window can be taken from a PNG file.
- in this PNG file, you may defined an area of an uniform color (tested with 'black' and 'white' so far) that can be identified and used, like implemented in this version, to wrap the dialog test in.

Remarks :
- at this state (8f91adc) the code has still much debug output that needs to be cleaned but I'm still working on it.
- I had some noob difficulties (maybe due to late hour) with pyglet stuff (subtleties related to pyglet.image.ImageData, to unexplained variations of data types in pyglet raw images,

Next step :
- the Player avatar should be displayed using the same color area system
- the dialog location should be binded to some other sprite's location (as for a nurse that may speak while walking in the corridor). Maybe it takes place in a wider-scale work on hierarchical relations/binding between objects (object conditionning ?).
- and of course the remaining TODO from you previous comment

**Comment by MatthieuPerrot** [comment]
Yes, the history of this branch is an actual mess, but I will take it as a trial-and-error side-damage.

Some very usefull things have been commited, mainly automatic text wrapping and backround image.

List of things to be adressed before merging the pull request (I repeat some of your comments) :
- answer to the commented piece of code which need it
- test your code with the pygame backend. You don't have to inplement your find_color_area method, but you have to verify that you code do not use specificities from pyglet apart from the pyglet backend.
- implement the area strategy for avatar sprite
- offer a way to replace color of the area by a user-defined one
- the area stategy (avatar + text) should be optional. Manual definition of the text area and the relative avatar location should remain possible.
- previous comments about dialog listener.

I think the relative location of dialog anchored on another sprite should be delayed after this pull request.

**Comment by xgrg** [comment]
So, most of the cited features are still missing but still, let's merge the branch at this early stage so that we can go on with Motion etc...

The code was not tested with the pygame backend but I've checked that pyglet is only mentioned in the pyglet backend. The reason it was not tested with pygame is that replacing `pyglet` by `sdl` in an example reveals an error in the `sdl_backend`, which apparently was already in anterior versions.

The DialogContext now has an option `text_area_mode` to choose between two modes concerning the text wrapping method : the old mode, where the text area is defined from the dialog dimensions (now from the PNG file used as the dialog layout) or defined after detecting an area of specific color in the PNG file.

**Comment by MatthieuPerrot** [comment]
I think it is not the best thing to do for the quality of the main repository master branch. But it seems to be a quite reasonable quick and dirty solution to resolve most pending pull requests. So, ok merge it ! And we will try to reopen this pull request afterwards.

**Pull request merged**
