### PR TITLE
Add Clipping capacity to virtual screen in pyglet backend

### PR DESCRIPTION
**Pull request by MatthieuPerrot**
I had an additional example mixed 2 contexts (one with 2 half-screens and another covering the whole window).

### CODE REVIEW

**Comment by xgrg** [comment]
Where are the two half-screens ?
python test_two_screens.py give me only one VirtualScreen following the player (but without being centered) with Pause over everything.

**Comment by MatthieuPerrot** [comment]
Pause over everything follows the normal behaviour. But you should see 2 screens split vertically underneath. Each half-screen focused on a specific player. I don't know why this does not work for you.

In your case, does the uniq VirtualScreen fill the whole screen ?

**Comment by xgrg** [comment]
I can see the two characters moving in the scene. I can guess the right part of the screen is centered on the player character (PC) but still the PC's screen seems to take over the left part too.

And plus, the Pause button is not responsive.

**Comment by MatthieuPerrot** [comment]
- They are no Pause action, the Pause sprite has been used to show another context above the split screen.
- In my case (tested on 3 PC, including using NX), the left screen is centered on the "nurse" and right screen on the "player". Both left/right screens share a same context including a background, the nurse and the player.

I am wondering if my example is work on your computer (pyglet/opengl issue ?) or if you misunderstood my example.

**Comment by MatthieuPerrot** [comment]
I just made some changes in your test to make it work after the introduction of clipping in the pyglet backend.

**Comment by MatthieuPerrot** [comment]
mmm. I think we had bad practice with git since we don't use branches and accidentally mixed my pull request and yours from last night. I will try to untangle a bit the network of our last commits by first resolving my pull request. Then we will discuss about yours.

**Pull request closed without merging**
