### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by xgrg**
Now it is my turn to request a pull from my brand new small-changes branch, which contains various tweaks : some of them are either (stupid) docstrings updates, some others are changesets that seemed to be contained in the master version but which disappeared for some reason (@10fbe8de and following), some others are (easy) examples. In one word, only small changes !

### CODE REVIEW

**Comment by MatthieuPerrot** [comment]
you should fusion @52e4f12 and @cb7ce0b since both concern storing the layer of a given sprite.
About this 2 commits and @a8a627e: we should first merge my small_changes pull request and then consider yours with the implied changes.

**Comment by MatthieuPerrot** [comment]
ok well done. Let's resolve my small_changes pull request

**Comment by xgrg** [comment]
After our last merge in the-nurse-project/master (@a31d6a3f), a commit of mine had to be corrected to solve a conflict.
Now if you're ok with this we may try to integrate this set of commits as well, so that we can work out the remaining pull requests.

**Comment by MatthieuPerrot** [comment]
ok for me, merge !!!

**Pull request merged**
