### PR TITLE
API proposal of signal-slots connections resolving conditionnaly to spatial data

### PR DESCRIPTION
**Pull request by MatthieuPerrot**
The idea is to put some bases to a gameplay similar to "One Chance" game.

The point of this pull-request focuses on spatially conditioning calls to a given named slot by selecting those sprites which spatially intersect a given targeted sprite. This may sound too specialized, but I did not manage to find a more general user-case.
- Sprite: add a bounding box in absolute virtual coordinates.
- Object: add a unique entry point "call_slot" of any slots call. This allowes to wrap those calls and do customized stuffs around it.
- examples/test_spatial_event.py: an example illustrating the proposal. Some API objects are voluntarily misplaced and defined here for commodity to simplify the tests and comments on this API.
- examples/test_spatial_event2.py: a more complex example.

### CODE REVIEW

**Comment by xgrg** [comment]
This comment is only concerned with two commits from this pull request, i.e. @a4d5f37 and @c542e16 (edit: no longer existing now)
The name 'on_collision' might create confusion since it is used as a slot name for the keyboard event _and_ for the 'real' collision event which seems to be processed by the CollisionManager. These two distinct names should be decorrelated so that the "on_key_press" slot would be able to call the "on_collision" slot of the collidable object.

MoveSquaresOnCollision is used to manage the collision with the nurse : therefore the class name is confusing.

I can imagine the aim of the ObjectProxy class. Still, it makes the class tree a little more complex for the limited outcome I could perceive. But fine, since it is assumed to make the whole thing generic with the 'call_slot' method.

Indeed, ObjectProxy and ConditionalObject should take place in base.py while CollisionManager is more related  to sprites.

**Comment by MatthieuPerrot** [comment]
- The on_collision slot is called _only_ when the CollisionManager catch a specific keyboard event on the first sprite in collision with the sprite of reference. Hence, we can't tell 'real' or 'fake' collision, only «collision detected after a key event». I don't understand your comment about 'on_key_press' slot.
- I rename MoveSquaresOnCollision -> ManageCollision.
- ObjectProxy: The idea is that we have to propose a set of useful generic and current Sprites, but we can provide specific behaviour and collision handling is often specific. But we are still able to decorate/wrap such an object through the ObjectProxy mechanism. I think this behaviour could become a common practice in game. Maybe we should do an example/classic games driven sprint to answer correctly to your comment.
- ok to move the class in base.py

**Comment by xgrg** [comment]
> _The oncollision slot is called _only when the CollisionManager catch a specific keyboard event on the first sprite in_ 
> _collision with the sprite of reference. Hence, we can't tell 'real' or 'fake' collision, only «collision detected after a key_ 
> _event». I don't understand your comment about 'on_key_press' slot._

OK forget it this was probably a false problem. We'll talk about this directly if needed.

For now, the collision-related stuff is located in sprite.py since it is related to sprites. Of course at this stage the collision detection is quite a low-level sprite-oriented simple process but maybe (or in the future) this would have more to do with the physics engine. It is just a suggestion so that the code remains optimally distributed and our minds optimally focused.

@0aa945f42bf09eb1 may conflict with the dialog branch merge. As I wrote in the other pull request, maybe we should first merge the dialog branch and then this one.

**Comment by MatthieuPerrot** [comment]
> For now, the collision-related stuff is located in sprite.py since it is related to sprites. Of course at this stage the collision detection is  quite a low-level sprite-oriented simple process but maybe (or in the future) this would have more to do with the physics engine. It  is just a suggestion so that the code remains optimally distributed and our minds optimally focused.

Yea, I hope so ! Maybe we could begin with standard games like pong or breakout to define some bases to a more generic collission management. But, we can try to code a «one-chance»-like game right know !

> @0aa945f42bf09eb1 may conflict with the dialog branch merge. As I wrote in the other pull request, maybe we should first merge  the dialog branch and then this one. 

ok let's finish your dialog branch first.

**Pull request merged**
