### PR TITLE
Motion

### PR DESCRIPTION
**Pull request by MatthieuPerrot**
- Reworked and clarified the sprites API
- First proposal for the motion API. A motion is a class controling the
  location of a sprite. This includes computer-based strategy (following
  a path) or player-based strategy (using keyboard). Motions could be applied
  to all kind of sprites (static, animated, uniform layers, dialog, text,
  fps, ...)
- Add 2 examples illustrating what could be done with this API. Currently, the dialog sprites does not benefit from this new API. Since @xgrg is working on dialogs, we should test with his branch if the dialog motion behaviour is correct.

### CODE REVIEW

**Comment by xgrg** [comment]
Interesting work.
- What is a `StaticMotion` ?
- We should indeed come to a merge quite soon, for the reason the sprite module finds some evolution here while the dialog branch also has some pending changes on it. After comparing the extent of the changesets, I suggest we merge the dialog branch first.

The example falling_squares which uses these enhancements was successfully tested on my machine. I have no remarks on the API at this stage.

**Comment by MatthieuPerrot** [comment]
- `StaticMotion` might not be the best name, but it refers to an empty/none motion. I am waiting for your suggestions to find a more suitable name.
- ok, dialog branch first

**Comment by xgrg** [comment]
- mmm... NoMotion, MotionLess, RestingState ? ;-)
- I suggest that some (even simple) docstrings should be written for the new classes implemented in this pull request. The interest is at least twofold : it would help code reading and it would be used by Sphinx when generating documentation.

**Comment by MatthieuPerrot** [comment]
- ok for `NoMotion`
- you are right for the lack of documentation, i will add some soon

**Comment by MatthieuPerrot** [comment]
The 2 above points were cleared !

**Pull request merged**
